### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by agamsanghera** [UBC-MDS/group04#18]
@agendazhang added basic analysis, but a couple of changes need to be made and I will do them now. A logistic regression model would be better used than a decision tree regressor, and that was not used in DSCI 571 either. The column used for prediction should be "Route" while that has not been used, using 'Min Gap' would not be a good idea as that is calculated based on our target variable, which would be training the model with incorrect .  Performance metrics, and cross validation need to be added as part of the analysis. As mentioned, I will do the aforementioned, but it would be good practice to keep in mind for next time

**Comment by agamsanghera** [comment]
Completed the mentioned tasks, now only the description is remaining, @agendazhang is working on it

**Comment by agendazhang** [comment]
Completed in milestone 1
