### ISSUE TITLE
Document how to update Docker image

### ISSUE THREAD

**Issue by agendazhang** [UBC-MDS/group04#31]
- Document how to use and update your container image in your README as this is important to make it easy for others to shift to a container solution for your computational environment
- Use Docker Compose so that launching your containers is as frictionless as possible

**Comment by agamsanghera** [comment]
The current docker-publish isn't working, I am working on fixing that and deploying the changes in the dockerhub branch

**Comment by agendazhang** [comment]
@agamsanghera I have already fixed that, take a look at the other issue thread.

**Comment by agendazhang** [comment]
This task has been completed as per https://github.com/UBC-MDS/group04/pull/33
