### ISSUE TITLE
Creating Scripts

### ISSUE THREAD

**Issue by diwanashita** [UBC-MDS/group04#39]
- Data validation @diwanashita 
- EDA @diwanashita 
- Creating Model/Analysis @agamsanghera 
- Analysis based on the model @agamsanghera

**Comment by ch3ch20h** [comment]
Hi team, how is everyone progressing with their tasks?

**Comment by agamsanghera** [comment]
We had quizzes this week, so I am just starting now

**Comment by agamsanghera** [comment]
Completed the pre processsing.py script and pushed it to the scripts branch
